spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CNPayment?createDatabaseIfNotExists=true
    username: root
    password: jojojo2002
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate-dialect:  org.hibernate.dialect.MySQLDialect